apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-volume-1
  namespace: default
  labels:
    app: plan-manage
    type: storage
spec:
  storageClassName: slow
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/pv01"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-volume-2
  namespace: default
  labels:
    app: plan-manage
    type: storage
spec:
  storageClassName: slow
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/pv02"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-volume-3
  namespace: default
  labels:
    app: plan-manage
    type: storage
spec:
  storageClassName: slow
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/pv03"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgres-secret
  namespace: default
  labels:
    app: plan-manage
    type: database
data:
  root_password: UGFzc3dvcmQ=
  root_username: YWRtaW4=
  keyfile: eGg5Z2JVaDdNWlVlVVhQVlZQT2RxdW9hWjh5bzZKMzVjellXcXc3cTR5Q2V3M1VqbWVieXVLNGYyNGdhaE81ZXpHSFFhQnYwTjgxSi9jb2Qvc3d4QmN3aGxLZGJoVjhUZVhUL09YM0JteEtWaTkreXhHeWZzd05BWElvSFhDaFFScUdSKy9qbkl6UE53SUV5K0hycWFOdWh0aVd0U0ltYTlXS0lBcHVxYXNQeFRaUlFRNWRvTVpmYldlSzhGYTc4bUN3WklmNUlKbEVwMmRtdUZRNUFoTEpINEhHa3ptMEEvMW1INW9Bb2hYRGwvTVpGRlhJNXlmSVlwZ1pQREVTTE9EZGR1QVlibHZBMllDZnFFVDB3V3hmZlRBbXNXMjl4STRDbnlDYXhHNUpVYnU2RTI4MHhFam02NUoyQU16eWNOTXZRUlluRjdtdGdGNzAwU0dSdWhaUDhTU0w2d0lGekl2bWJMUEFUWFFEanpuTERMZkp1ZkFqbzNDWDdBN2JCL3ZUc0VsQUhpM1orNTFiOURuOTBwUENLMHRBRGIyZUk3RVhyZEw0VEY1THJMYmRzNWc3T1ZSeEtWNSt6ZFcwUDQ2QjJDSjd0ck1Ia0tIbVRJSHJSUWtRTXVRUS85d2c5aHhXVkVDV0FNWFhJRmxMTjFIcFBZRndoMVcyVGxjcFFPRzQxSStHWkZlVHNGMFFWL056TmRKWVNuNmxhREZRd2ZQWEVic0ZONEFDMkh0UUxHWE1nWU85OVF3ZVRVY3llRHBUTnNCczNXc016YlpkMStnWHNYQkc5Vzg5eXg5Y3JZUTllQ214a3RFYTQ1bm9JbnM4MWEvYUg2OVRtVUlrU1ZuZVcrTm9VYWE2MzN3OUZUc2ZMekFwNlZaYzZ4aGpieWdXZDQ2SitWeU1oYjN6ell1a0ZET01saU4xT3I4ek5BdGoxTDBOMWxjalQvSVhMNlBiczQ3NVBMS2ExclAwTy9acVk3ZUlCb09ncnNUUWtsOURNQXFLNEtoOFhhYjhJZjd2K0FXTG5NNUxPUU80M3o5TTlKSTJEWjVkZi9VOGZWVWRSV3o5OVRXQkUvajdibDhzdG1MRnI2ME9ZK3NqazFMWGd3SHFXOWYyRUlhU3ByK2dFaW14cXA1WnlvVjA2cWV5V1ZicGlUQXRnaEhmNzBUWnRhbVRDMkJFQ1U0S2E3RXFCMFFMbERBS0k0eWpISThhY3JkNXYwbXhLTmY2OHJvRm15ZTl4eXAza2Y1ZDRKL3haUDBUd21zdGg0N0FTaWFyWisyU3hUU0doT1U1OUlvUlp6bXpTQmE3aHUwRXlQMWlIMXhyVXlLRG00OHZlWVRjTkg3N2oxcWdqWi8vNwo=
---
apiVersion: v1
kind: Service
metadata:
  name: db-svc
  namespace: default
  labels:
    app: plan-manage
    type: database
spec:
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
  selector:
    app: plan-manage
    type: database
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: default
  labels:
    app: plan-manage
    type: database
spec:
  selector:
    matchLabels:
      app: plan-manage
      type: database
  serviceName: db-svc
  replicas: 3
  template:
    metadata:
      name: postgres
      namespace: default
      labels:
        app: plan-manage
        type: database
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: postgres
          image: postgres:14-alpine
          # commandにするとDockerのENTRYPOINTが上書きされてしまうため
          args:
            - "posgre"
            - "--auth"
            # replicaSetで動かす際の設定
            - "--clusterAuthMode=keyFile"
            - "--keyFile=/home/postgredb/keyfile"
            - "--replSet=rs0"
            - "--bind_ip_all"
          env:
            - name: "POSTGRES_USER"
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: root_username
            - name: "POSTGRES_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: root_password
            - name: "POSTGRES_INITDB_AGES"
              value: "--encoding=UTF-8"
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: "/data/db"
              name: storage
            - mountPath: /home/postgredb
              name: secret
      volumes:
        - name: secret
          secret:
            secretName: postgres-secret
            items:
              - key: keyfile
                path: keyfile
                mode: 0700
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        storageClassName: slow
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 1Gi
