apiVersion: v1
kind: Service
metadata:
  name: plan-manage-frontend-svc
  namespace: default
  labels:
    app: plan-manage
    type: application
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: plan-manage
    type: application
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
  labels:
    app: plan-manage
    type: application
spec:
  replicas: 3
  selector:
    matchLabels:
      app: plan-manage
      type: application
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  revisionHistoryLimit: 14
  template:
    metadata:
      name: frontend
      namespace: default
      labels:
        app: plan-manage
        type: application
    spec:
      containers:
        - name: plan-manage-frontend
          image: plan_manager_frontend
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
